BDIR = ./build
SDIR = ./src

make:
	g++ -c ${SDIR}/vectors.cpp -o ${BDIR}/vectors.o
	g++ -c ${SDIR}/render.cpp -o ${BDIR}/render.o
	g++ -c ${SDIR}/main.cpp -o ${BDIR}/main.o
	g++ -o ${BDIR}/main ${BDIR}/main.o ${BDIR}/vectors.o ${BDIR}/render.o

run:
	${BDIR}/main